services:
  mysql:
    image: mysql:8.0
    container_name: ms_mysql
    environment:
      MYSQL_ROOT_PASSWORD: TheKing
      MYSQL_DATABASE: zzootecdb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3308"
    networks:
      - microservices-net
    restart: unless-stopped

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  microservices-net:
    driver: bridge

volumes:
  mysql_data: