spring:
  application:
    name: msvc-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9099/realms/zzootec"