server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: products
          uri: "http://localhost:8090"
          predicates:
            - Path=/api/v1/product/**
        - id: users
          uri: "http://localhost:8091"
          predicates:
            - Path=/api/v1/user/**

#security:
#  oauth2:
#    resourceserver:
#      jwt:
#        issuer-uri: http://localhost:9090/realms/zzootec-realm
