server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: products
          uri: "http://localhost:8090"
          predicates:
            - Path=/api/v1/product/**
        - id: users
          uri: "http://localhost:8091"
          predicates:
            - Path=/api/v1/user/**
