server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: products
          uri: "http://localhost:8090"
          predicates:
            - Path=/api/product/**
        - id: categories
          uri: "http://localhost:9090"
          predicates:
            - Path=/api/category/**
eureka:
  client:
    register-with-eureka: false
