server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: products
          uri: "http://localhost:8090"
          predicates:
            - Path=/api/v1/product/**

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:9090/realms/zzootec-realm

eureka:
  client:
    register-with-eureka: false
