server:
  port: 8040
spring:
  application:
    name: notification-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/zzootecdb
    username: gutz
    password: gutz
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: 'com.zzootec.ecommerce.kafka.*'
        spring.json.type.mapping: "orderConfirmation:com.zzootec.ecommerce.kafka.order.OrderConfirmation,paymentConfirmation:com.zzootec.ecommerce.kafka.payment.PaymentConfirmation"

  mail:
    host: localhost
    port: 1025
    username: gutz
    password: gutz
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

management:
  tracing:
    sampling:
      probability: 1.0